//SQL : Langage de requetes structurees
//SGBDR : SYSTEMES DE GESTION DES BASES DE DONNEES RELATIONNELLES (LOGICIEL : ACCESS , sql server, MYSQL SERVER, ORACLE, POSTGESQL)
//BASE DE DONNNEES RELATIONNELLES:
    -- PHYSIQUEMENT  : FICHIER DANS LE DISQUE DUR GERE PAR LE SGBDR
    -- LOGIQUEMENT  : ENSEMBLE DE TABLES RELATIONNELLES

-- SQL :
-- ldd : LANGAGE DE DEFINITION DES DONNEES  : CREATE , DROP , ALTER
--lmd : LANGAGE DE MANIPULATION DES DONNEES :    , UPDATE , DELETE
-- lid : LANGAGE D'INTEROGATION DES DONNEES : SELECT

